INSERT INTO `cp_configure` VALUES ('1', 'block_message', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('2', 'block_is_enable', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('3', 'block_start_time', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('4', 'block_end_time', '', '0','0', '0');
INSERT INTO `cp_configure` VALUES ('5', 'email_host', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('6', 'email_port', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('7', 'email_username', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('8', 'email_password', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('9', 'email_from', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('10', 'email_is_ssl', '', '0', '0', '0');
INSERT INTO `cp_configure` VALUES ('11', 'email_cc_list', '', '0', '0', '0');
